In [3]:
import numpy as np
from sklearn.linear_model import LinearRegression
# from econml.dr import DRLearner



In [4]:
n = 1000

# Treatment
t = np.random.choice([0,1],n)

# Gender
g = np.random.choice([-1,1], n)

# Noise
e = np.random.randn(n) * 1000

# Outcome
y = g * t * 100 + 500 + e

# ATE model
lr = LinearRegression()
lr.fit(t.reshape(-1,1), y)

# Instantiate the CATE model
est = DRLearner()

# Fit the model
est.fit(y, t, X=g.reshape(-1,1))

# Estimate the effect for gender -1
cate_minus = est.effect(X=np.array([[-1]]))

# Estimate the effect for gender +1
cate_plus = est.effect(X=np.array([[1]]))


print(f'ATE: {lr.coef_}\nCATEs: {cate_minus}, {cate_plus}')

NameError: name 'DRLearner' is not defined

In [5]:
n = 1000

# Treatment
t = np.random.choice([0,1],n)

# Gender
g = np.random.choice([-1,1], n)

# Noise
e = np.random.randn(n) * 1000

# Outcome
y = g * t * 100 + 500 + e

# ATE model
lr = LinearRegression()
lr.fit(t.reshape(-1,1), y)

LinearRegression()

In [30]:
lr.predict(([[0]]))

array([529.83829878])

In [6]:
lr.predict(([[1]]))

array([503.62906105])

In [9]:
print(f'ATE: {lr.coef_}')

ATE: [-26.20923773]


In [15]:
print('intercept:', lr.intercept_)

intercept: 529.8382987803285


In [16]:
# ATE model
lr2 = LinearRegression()
lr2.fit(X, y)

LinearRegression()

In [17]:
print(f'ATE: {lr2.coef_}')

ATE: [-27.96591733   9.26463431  79.53775559]


In [18]:
lr2.intercept_

530.0060688181469

In [29]:


w = X[-1:]
lr2.predict(w)

array([590.84254139])

In [25]:
X[-1:]

t  g  i
999  1  1  1